<?php
$labels_portfolio = array(
	'name'                  => _x( 'Portfolio', 'Post Type General Name', 'cmmp' ),
	'singular_name'         => _x( 'Portfolio', 'Post Type Singular Name', 'cmmp' ),
	// 'add_new'               => __( 'Add New', 'text_domain' ),
	// 'add_new_item'          => __( 'Add New Item', 'text_domain' ),
	// 'edit_item'             => __( 'Edit Item', 'text_domain' ),
	// 'new_item'              => __( 'New Item', 'text_domain' ),
	// 'view_item'             => __( 'View Item', 'text_domain' ),
	// 'search_items'          => __( 'Search Portfolio', 'text_domain' ),
	// 'not_found'             => __( 'Not found', 'text_domain' ),
	// 'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
	// 'all_items'             => __( 'All Portfolio items', 'text_domain' ),
	'archives'              => __( 'Portfolio', 'text_domain' ),
	// 'insert_into_item'      => __( 'Insert into Portfolio', 'text_domain' ),
	// 'uploaded_to_this_item' => __( 'Uploaded to this item', 'text_domain' ),
	// 'featured_image'        => __( 'Featured Image', 'text_domain' ),
	// 'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
	// 'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
	// 'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
	// 'menu_name'             => __( 'Post Types', 'text_domain' ),
	// 'filter_items_list'     => __( 'Filter items list', 'text_domain' ),
	// 'items_list_navigation' => __( 'Items list navigation', 'text_domain' ),
	// 'items_list'            => __( 'Items list', 'text_domain' ),
	// 'name_admin_bar'        => __( 'Post Type', 'text_domain' ),
);

$args_portfolio = array(
	'labels'                => $labels_portfolio,
	'public'                => true,
	'menu_position'         => 5,
	'menu_icon'             => 'dashicons-welcome-learn-more',
	'hierarchical'          => false,
	'supports'              => array(
		'title',
		'editor',
		'thumbnail',
		'custom-fields',
		'revisions',
		'page-attributes',
	),
	// 'register_meta_box_cb'  => ,
	// 'taxonomies'            => array( 'category', 'post_tag' ),
	'has_archive'           => true,
);
register_post_type( 'portfolio', $args_portfolio );
